### ISSUE TITLE
[severity_high_security] Improve the severity nags for sec-high bugs

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbot#1443]
##### @dveditz suggested the following:
> check the `status-firefox` fields and only nag if it's `affected` (and maybe `---`) for the current releases, or skip nagging if it's explicitly `disabled` or `unaffected` for current releases.

**Comment by dveditz** [comment]
It looks like the nag I was talking about is from #1336 / #1348.

I skimmed the names and topics of the files in the scripts folder and didn't see any others that seemed relevant, but I wanted to be clear that I have only been bothered by this one specific nag. It's possible "disabled" status is relevant to other nags, but that should be reasoned about case-by-case (I could equally imagine cases where the nag shouldn't care) and not be lumped in with this specific request.

**Comment by marco-c** [comment]
I think it's preferable to have the severiy for a bug be the severity as if that bug belonged to an enabled feature. For example, this allows us to correctly estimate the severity of bugs blocking a given feature.
If we set all the severities of bugs blocking a new feature as S3/S4 just because the feature is not released yet, we have no easy way to estimate the quality of that feature when we have to decide if we want to ship it or not.

**Comment by gcp** [comment]
>I think it's preferable to have the severiy for a bug be the severity as if that bug belonged to an enabled feature.

Another good reason for this is that we have been pwned by features that were disabled, by attackers using the (still active) IPC surface for the disabled feature.

**Comment by dveditz** [comment]
@marco-c was talking about the literal "severity" field. The reasoning is the same that leads us to want to leave the security-severity high even if a feature is currently disabled. It would be hypocritical of me to disagree, but accepting that would essentially mean a WONTFIX on this issue.

That doesn't solve the problem that developers feel management pressure to resolve all the S2 bugs ASAP, adding to the pressure to address sec-high bugs ASAP. On their own the sec-high issue isn't too bad: the ABU metric takes disabled bugs into account.

If we change this rule to ignore disabled sec-high bugs, wouldn't the rule come back later and nag once the bug is not disabled?

Another solution to the problem could be to address how the S2 KPI metric is calculated. If that burn down ignored disabled bugs that would take away the reason developers hate this particular nag.

**Comment by suhaibmujahid** [comment]
> If we change this rule to ignore disabled sec-high bugs, wouldn't the rule come back later and nag once the bug is not disabled?

Yes, it will do.

> If that burn down ignored disabled bugs that would take away the reason developers hate this particular nag.

I support ignoring bugs related to disabled features if doing so will make the rule less noisy.
